-- =============================================
-- Stock News LangGraph System — Supabase Schema
-- =============================================

-- =============================================
-- Extensions
-- =============================================
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- =============================================
-- tickers (stock master)
-- =============================================
CREATE TABLE tickers (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  symbol       TEXT        NOT NULL UNIQUE,   -- e.g. 'AAPL', 'TSLA'
  company_name TEXT        NOT NULL,          -- e.g. 'Apple Inc.'
  sector       TEXT,                          -- e.g. 'Technology'
  industry     TEXT,                          -- e.g. 'Consumer Electronics'
  is_active    BOOLEAN     NOT NULL DEFAULT true,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  tickers            IS 'Stock master table';
COMMENT ON COLUMN tickers.symbol     IS 'Ticker symbol (e.g. AAPL)';
COMMENT ON COLUMN tickers.sector     IS 'Broad sector from yfinance (e.g. Technology)';
COMMENT ON COLUMN tickers.industry   IS 'Specific industry from yfinance (e.g. Consumer Electronics)';
COMMENT ON COLUMN tickers.is_active  IS 'Set to false to deactivate a ticker without deleting it';

-- =============================================
-- stock_news (news + summary + sentiment)
-- =============================================
CREATE TABLE stock_news (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  ticker_id        UUID        NOT NULL REFERENCES tickers(id) ON DELETE CASCADE,

  -- original article
  title            TEXT        NOT NULL,
  content          TEXT,                       -- full text fetched from Tavily
  raw_content      TEXT,                       -- raw content fetched from Tavily
  source_url       TEXT,  
  published_at     TIMESTAMPTZ,

  -- LLM analysis results
  summary          TEXT,                       -- English summary
  summary_kr       TEXT,                       -- Korean translation
  sentiment        TEXT        CHECK (sentiment IN ('positive', 'negative', 'neutral')),
  sentiment_score  FLOAT       CHECK (sentiment_score BETWEEN -1.0 AND 1.0),

  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  stock_news                  IS 'News articles with LLM analysis results';
COMMENT ON COLUMN stock_news.content_original IS 'Raw article text retrieved from Tavily API';
COMMENT ON COLUMN stock_news.summary          IS 'English summary generated by LLM';
COMMENT ON COLUMN stock_news.summary_kr       IS 'Korean translation generated by LLM';
COMMENT ON COLUMN stock_news.sentiment_score  IS '-1.0 (very negative) to 1.0 (very positive)';


-- =============================================
-- Indexes
-- =============================================

-- tickers
CREATE INDEX idx_tickers_symbol    ON tickers(symbol);
CREATE INDEX idx_tickers_sector    ON tickers(sector);
CREATE INDEX idx_tickers_industry  ON tickers(industry);
CREATE INDEX idx_tickers_is_active ON tickers(is_active);

-- stock_news — general lookups
CREATE INDEX idx_stock_news_ticker_id  ON stock_news(ticker_id);
CREATE INDEX idx_stock_news_published  ON stock_news(published_at DESC);
CREATE INDEX idx_stock_news_sentiment  ON stock_news(sentiment);
CREATE INDEX idx_stock_news_created    ON stock_news(created_at DESC);

-- stock_news — composite index for ticker + date range queries
CREATE INDEX idx_stock_news_ticker_pub ON stock_news(ticker_id, published_at DESC);